site_name: LoopDocs
theme: flatly
google_analytics: ['UA-109876065-1', 'loopkit.github.io']
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- Home: 'index.md'
- FAQs:
    - 'Using This Site FAQs': 'faqs/docs-faqs.md'
    - 'General Loop FAQs': 'faqs/FAQs.md'
    - 'Omnipod FAQs': 'faqs/omnipod-faqs.md'
    - 'RileyLink FAQs': 'faqs/rileylink-faqs.md'
    - 'Algorithm FAQs': 'faqs/algorithm-faqs.md'
    - 'CGM FAQs': 'faqs/cgm-faqs.md'
    - 'Safety Tips': 'faqs/safety-faqs.md'
    - 'Glossary': 'faqs/glossary.md'
- Gear:
    - 'Insulin Pump':
        - 'Medtronic': 'setup/requirements/mdt-pump.md'
        - 'Omnipod': 'setup/requirements/omnipod-pump.md'
    - 'CGM': 'setup/requirements/cgm.md'
    - 'RileyLink': 'setup/requirements/rileylink.md'
    - 'Computer': 'setup/requirements/computer.md'
    - 'iPhone': 'setup/requirements/iphone.md'
    - 'Apple Developer': 'setup/requirements/appledev.md'
- Build App:
    - Overview: 'build/overview.md'
    - 'Step 1 Check Computer': 'build/day1.md'
    - 'Step 2 Compatible iPhone/iPod touch': 'build/day2.md'
    - 'Step 3 Compatible Pump': 'build/day3.md'
    - 'Step 4 Order a RileyLink': 'build/day4.md'
    - 'Step 5 Enroll in Apple Developer Program': 'build/day5.md'
    - 'Step 6 Install Homebrew': 'build/day6.md'
    - 'Step 7 Download Xcode': 'build/day7.md'
    - 'Step 8 Xcode Preferences': 'build/day8.md'
    - 'Step 9 Test Settings': 'build/day9.md'
    - 'Step 10 Make plans for Loop Data': 'build/day10.md'
    - 'Step 11 Meet Community': 'build/day11.md'
    - 'Step 12 Download Loop code': 'build/day12.md'
    - 'Step 13 Build Loop app': 'build/day13.md'
    - 'Oh dear! Build errors?': 'build/build_errors.md'
    - 'Jaeb Loop Study': 'build/jaeb-study.md'
    - 'Customize your Loop': 'build/code_customization.md'
    - 'Ready to Update your Loop?': 'build/updating.md'
- Set up App:
    - 'Overview': 'operation/overview.md'
    - Health Permissions: 'build/health.md'
    - 'Add Pump':
        - 'Add Medtronic': 'operation/loop-settings/mdt-pump.md'
        - 'Add Omnipod': 'operation/loop-settings/omnipod-pump.md'
    - 'Add CGM': 'operation/loop-settings/cgm.md'
    - 'Configurations': 'operation/loop-settings/configurations.md'
    - 'Loop Services': 'operation/loop-settings/services.md'
    - 'Loop Displays': 'operation/loop-settings/displays.md'
    - 'RileyLink menu': 'operation/loop-settings/rileylink.md'
- Operate:
    - How to Use Loop App:
        - 'Carb Entries': 'operation/features/carbs.md'
        - 'Bolus': 'operation/features/bolus.md'
        - 'Workout Targets': 'operation/features/workout.md'
        - 'Using ICE info': 'operation/features/ice.md'
        - 'Apple Watch': 'operation/features/watch.md'
        - 'iPhone widget': 'operation/features/widget.md'
        - 'Loop Notifications': 'operation/features/notifications.md'
        - 'Pump Battery': 'operation/features/battery.md'
    - 'Looping Tips':
        - 'Open Loop': 'operation/loop/open-loop.md'
        - 'Closed Loop': 'operation/loop/close-loop.md'
        - 'Loop Tips': 'operation/loop/looptips.md'
    - Algorithm:
        - 'Overview': 'operation/algorithm/overview.md'
        - 'Bolus Recommendations': 'operation/algorithm/bolus.md'
        - 'Glucose Prediction': 'operation/algorithm/prediction.md'
        - 'Temp Basal Adjustments': 'operation/algorithm/temp-basal.md'
    - Troubleshoot:
        - 'Overview': 'troubleshooting/overview.md'
        - 'Loop crashes': 'troubleshooting/loop-crashing.md'
        - 'Grey Loop': 'troubleshooting/green-loop.md'
        - 'Yellow/Red Loop': 'troubleshooting/yellow-red-loop.md'
        - 'Pod Pairing Failures': 'troubleshooting/pod-pairing.md'
        - 'MDT Priming and Sites': 'troubleshooting/priming.md'
        - 'Time Changes': 'troubleshooting/time-change.md'
        - 'MDT Pump Errors': 'troubleshooting/pump-errors.md'
        - 'Omnipod Faults': 'troubleshooting/omnipod-faults.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Brand New NS': 'nightscout/new_user.md'
    - 'Retrofit Existing NS': 'nightscout/update_user.md'
    - 'Setup Troubleshooting': 'nightscout/troublehoot.md'
    - 'NS Stopped Working': 'nightscout/mlab_cleanup.md'
    - 'Azure to Heroku': 'nightscout/azure_migration.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
